# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Junyi Xu's Academic Homepage"
title_separator          : "-"
name                     : &name "Junyi Xu (徐君仪)"
description              : &description "PhD Candidate at Institute of Automation, Chinese Academy of Sciences"
url                      : https://academicpages.github.io # 修改为您的GitHub Pages URL
baseurl                  : "" 
repository               : "academicpages/academicpages.github.io" # 修改为您的仓库名

# Site Author
author:
  # Biographic information
  avatar           : "profile.png" # 上传您的头像图片到/images/目录
  name             : "Junyi Xu (徐君仪)"
  pronouns         :  
  bio              : "PhD Candidate in Multi-Agent Reinforcement Learning and Drone Swarms"
  location         : "Beijing, China"
  employer         : "Institute of Automation, Chinese Academy of Sciences"
  uri              : # 可以添加个人网站URL
  email            : "your-email@example.com" # 修改为您的邮箱

  # Academic websites
  googlescholar    : "" # 添加您的Google Scholar链接
  orcid            : "" # 添加您的ORCID
  github           : "your-github-username" # 修改为您的GitHub用户名

  # Social media
  linkedin         : # 可添加LinkedIn用户名
  twitter          : # 可添加Twitter用户名

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# 其他设置保持不变...
